version: "3"

volumes:
  database-data:
  redis-data:

networks:
  app_network:
    external: false

services:
  db:
    container_name: devdb
    image: postgres:14
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app_network
    ports:
      - 5432:5432
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 3030:3000
    depends_on:
      - db
      - redis
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?schema=public
      DIRECT_URL: postgres://postgres:postgres@db:5432/postgres?schema=public
      SESSION_SECRET: abcdef1234
      MAGIC_LINK_SECRET: abcdef1234
      ENCRYPTION_KEY: ae13021afef0819c3a307ad487071c06
      REMIX_APP_PORT: 3000
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app_network
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8001:8081"
    networks:
      - app_network
    depends_on:
      - redis
