version: "3"

volumes:
  database-data:
  redis-data:
  redisinsight-data:

networks:
  app_network:
    external: false

services:
  db:
    container_name: devdb
    image: postgres:14
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app_network
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app_network
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8001:8081"
    networks:
      - app_network
    depends_on:
      - redis