version: "3"

volumes:
  database-data:
  redis-data:

networks:
  app_network:
    external: false

services:
  db:
    container_name: devdb
    image: postgres:14
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app_network
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app_network
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redis-data:/redisinsight